             PGM
             CPYF       FROMFILE(PJXI1D3ACE/ANAPF00F) +
                          TOFILE(PJXI1D3TST/ANAPF00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ANAPS00F) +
                          TOFILE(PJXI1D3TST/ANAPS00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ANAPG00F) +
                          TOFILE(PJXI1D3TST/ANAPG00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ANAPP00F) +
                          TOFILE(PJXI1D3TST/ANAPP00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ISANI00F) +
                          TOFILE(PJXI1D3TST/ISANI00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRLEG00F) +
                          TOFILE(PJXI1D3TST/PRLEG00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/OCLIV00F) +
                          TOFILE(PJXI1D3TST/OCLIV00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/OALIA00F) +
                          TOFILE(PJXI1D3TST/OALIA00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRACL00F) +
                          TOFILE(PJXI1D3TST/PRACL00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/MFEMV00F) +
                          TOFILE(PJXI1D3TST/MFEMV00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/MFEMM00F) +
                          TOFILE(PJXI1D3TST/MFEMM00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/MFSCO00F) +
                          TOFILE(PJXI1D3TST/MFSCO00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRCASS0F) +
                          TOFILE(PJXI1D3TST/PRCASS0F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ANNMR00F) +
                          TOFILE(PJXI1D3TST/ANNMR00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(HDAT/§MCOS00F) +
                          TOFILE(HDATTST/§MCOS00F) +
                          MBROPT(*REPLACE)
/* §§ */
             CPYF       FROMFILE(PJXI1D3ACE/PRACS00F) +
                          TOFILE(PJXI1D3TST/PRACS00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRACSS0F) +
                          TOFILE(PJXI1D3TST/PRACSS0F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRTCL00F) +
                          TOFILE(PJXI1D3TST/PRTCL00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/OCCAP00F) +
                          TOFILE(PJXI1D3TST/OCCAP00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRORT00F) +
                          TOFILE(PJXI1D3TST/PRORT00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/PRORM00F) +
                          TOFILE(PJXI1D3TST/PRORM00F) +
                          MBROPT(*REPLACE)
             CPYF       FROMFILE(PJXI1D3ACE/ANTCM00F) +
                          TOFILE(PJXI1D3TST/ANTCM00F) +
                          MBROPT(*REPLACE)
             ENDPGM
